name: Upload Artifact Example

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: step-1
        run: |
          {
            echo "variable=$(find . -type f -name 'output.txt' -printf "%p,")"
          } >> "$GITHUB_OUTPUT"

      - run: |
          sed -i 's+/home/runner/work/feeds-manager/feeds-manager/+/github/workspace/+g' ${{ steps.step-1.outputs.variable }}
