name: Upload Artifact Example

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - id: step-1
        run: |
          {
            echo "variable=$(find . -type f -name 'output.txt' -printf "%p,")"
          } >> "$GITHUB_OUTPUT"

      - run: |
          sed -i 's+/home/runner/work/feeds-manager/feeds-manager/+/github/workspace/+g' ${{ steps.step-1.outputs.variable }}
